server:
  service:
    type: LoadBalancer
  ingress:
    enabled: false
redis:
  enabled: true

controller:
  metrics:
    enabled: true
server:
  metrics:
    enabled: true
repoServer:
  metrics:
    enabled: true