server:
  service:
    type: LoadBalancer
  ingress:
    enabled: false
redis:
  enabled: true

controller:
  metrics:
    enabled: true
server:
  metrics:
    enabled: true
repoServer:
  metrics:
    enabled: true
configs:
  repositories:
    jimag-gitops:
      url: https://github.com/Jimag-Dev-Org/Jimag-GitOps.git
      usernameSecret:
        name: argocd-github-jimag-gitops
        key: username
      passwordSecret:
        name: argocd-github-jimag-gitops
        key: password
