name: Terraform destroy (dev)

on:
  workflow_dispatch:
    inputs:
      region:
        description: "AWS region"
        required: true
        default: "us-east-1"
        type: choice
        options:
          - us-east-1
          - us-west-2

# 🔹 Needed for GitHub OIDC → AWS
permissions:
  contents: read
  id-token: write

jobs:
  destroy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ inputs.region }}

      - name: Terraform init (dev)
        working-directory: live/dev/${{ inputs.region }}
        run: terraform init -input=false

      - name: Terraform destroy (dev)
        working-directory: live/dev/${{ inputs.region }}
        run: terraform destroy -auto-approve -input=false
